name: Chart CI
run-name: "Redcap CI triggered by @${{ github.actor }}"

on:
  workflow_call:
    inputs:
      chart-dir:
        description: "Directory holding your Chart"
        required: true
        type: string 
        default: "chart"
      chart-values:
          description: "Chart values file that will be used for the testing and scanning steps"
          required: false
          type: string 
          default: "chart/values.yaml"
      kubernetes-version:
        description: "Version of the target Kubernetes cluster the Chart will run on"
        required: false
        type: string 
        default: "1.24.2"


jobs:
  aphp-chart-ci-workflow:
    uses: "aphp/ci-workflows/.github/workflows/chart-ci.yml@main"
    with:
      kubernetes-version: ${{ inputs.kubernetes-version }}
      chart-dir: ${{ inputs.chart-dir }}
      chart-values: ${{ inputs.chart-values }}
