name: "ci-redcap"
run-name: "Redcap CI triggered by @${{ github.actor }}"

on:
  workflow_call:
    inputs:
      dockerfile-path:
        description: "Path to Dockerfile of your project"
        required: false
        type: string 
        default: "Dockerfile"
      image-name:
        description: "Image name"
        required: true
        type: string 

jobs:
  redcap-container:
    uses: "aphp/ci-workflows/.github/workflows/container-ci.yml@dev"
    with:
      dockerfile-path: ${{ inputs.dockerfile-path }}
      hadolint-ignore: "DL3008,DL3018,DL3041,SC2046"
      image-name: ${{ inputs.image-name }}
      image-custom-tag: ""
      extra-build-args: ""
      dockle-ignore: ""
      trivy-ignore-vuln-ids: ""
      trivy-ignore-license-ids: ""